server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app
    username: root
    password: Ashu@123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect